name: Build

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: php build.php

      - name: Upload
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts
          rsync -aiz --delete dist/ ${{ secrets.SSH_HOST }}:~/
